#!/usr/bin/env python3
"""Create a provenance-recorded RT-DETR runner that never opens the test split.

The validated detector harness lives beside the training collection rather than
in this repository. Screening uses an isolated generated copy, never edits the
active harness, and never instantiates its test dataset.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


PARSER_ANCHOR = '    parser.add_argument("--hflip", action="store_true",\n                        help="Enable only for an audited flip-safe taxonomy.")\n'
TEST_DATASET_ANCHOR = '    test_set = CocoPackDataset(pack_root, "test", processor, None)\n'
TEST_LOADER_ANCHOR = '    test_loader = DataLoader(test_set, shuffle=False, **kwargs)\n'
TEST_EVALUATION_ANCHOR = '    best_model = RTDetrForObjectDetection.from_pretrained(best_dir).to(device)\n'


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def replace_once(source: str, old: str, new: str, name: str) -> str:
    if source.count(old) != 1:
        raise ValueError(f"Could not safely locate exactly one {name} anchor")
    return source.replace(old, new, 1)


def prepare(source: str) -> str:
    source = replace_once(
        source,
        PARSER_ANCHOR,
        PARSER_ANCHOR + '    parser.add_argument("--skip-held-out-test", action="store_true", help="Screen on validation only; never read test annotations or images.")\n',
        "argument parser",
    )
    source = replace_once(source, TEST_DATASET_ANCHOR, '    test_set = None if args.skip_held_out_test else CocoPackDataset(pack_root, "test", processor, None)\n', "test dataset")
    source = replace_once(source, TEST_LOADER_ANCHOR, '    test_loader = None if args.skip_held_out_test else DataLoader(test_set, shuffle=False, **kwargs)\n', "test loader")
    source = replace_once(
        source,
        TEST_EVALUATION_ANCHOR,
        '    if args.skip_held_out_test:\n        write_json(args.output / "validation_only.json", {"selection": "best validation COCO mAP checkpoint; held-out test intentionally unopened", "best_validation": json.loads((best_dir / "best_validation.json").read_text(encoding="utf-8"))})\n        print(json.dumps({"validation_only": True}, sort_keys=True), flush=True)\n        return\n\n' + TEST_EVALUATION_ANCHOR,
        "test evaluation",
    )
    return source


def main() -> int:
    args = parse_args()
    original = args.source.read_text(encoding="utf-8")
    generated = prepare(original)
    digest = hashlib.sha256(original.encode("utf-8")).hexdigest()
    header = (
        "# GENERATED by prepare_rtdetr_validation_runner.py; do not edit.\n"
        f"# Source SHA-256: {digest}\n"
        "# This copy is validation-only and intentionally never opens the held-out test split.\n"
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header + generated, encoding="utf-8")
    print(f"Prepared validation-only runner from {args.source} ({digest})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
