"""Author source-bounded Rank 27 ground truth."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]; AUDIT=ROOT/'ground_truth'; IDENT='27__vol1__21'; WORK=AUDIT/'work'/IDENT
def put(n,v): WORK.mkdir(parents=True,exist_ok=True); (WORK/(n+'.json')).write_text(json.dumps(v,indent=2)+'\n')
def a(i,p,b,t): return {'id':i,'page':p,'bbox':b,'expected':t,'mode':'contains'}
def table(i,p,s,t,x0,x1,ys,rows): return {'id':i,'page':p,'sheet':s,'title_as_printed':t,'columns':'literal_source_row_as_printed','x_edges':[x0,x1],'y_ranges':ys,'rows':rows,'row_reading_order':'left_to_right','source_row_semantics':'Literal source row only; it is not an installed quantity, controller binding, ownership or wiring assertion.'}
def pages():
 def f(p):
  if p==1:return 'Cover sheet visually reviewed; project identity retained.'
  if p in {52,53,54,55,56}:return 'M-701 through M-705 controls sheet visually reviewed; sequences, diagrams and limited matrix/schedule evidence retained separately.'
  if p==30:return 'Plumbing/equipment schedule source sheet visually reviewed; a literal booster-pump schedule row retained.'
  if 47<=p<=51:return 'Mechanical details/schedules source sheet visually reviewed as coordinated context.'
  if 31<=p<=46:return 'Mechanical plan/detail source sheet visually reviewed as coordinated context.'
  return 'General/architectural/structural/electrical source sheet visually reviewed as coordinated context.'
 return [{'page':p,'sheet_context':f'PDF {p:03d}','render':f'reviews/{IDENT}/p{p}-p{p}-full-poppler.png','finding':f(p)} for p in range(1,129)]
def audit():
 ds=[('project_identity','Cover title identifies Orange County Public Safety Building.',[['modules','metadata','project']]),('sheet_details','All 128 pages have visual-review records; M-701–M-705 are retained control sheets.',[['modules','metadata','visual_review_pages']]),('scale_verification','No global scale or plan quantity is asserted.',[['modules','metadata','scale_semantics']]),('equipment_tags_and_classification','One literal booster-pump schedule row is retained without installed-multiplicity inference.',[['modules','equipment_reconciliation','schedule_counts']]),('schedule_rows_and_specs','The retained schedule row is coordinate-bounded.',[['modules','schedules','tables']]),('point_lists_and_equipment_ownership','One literal chilled-water control-diagram I/O row is retained; physical ownership is explicit as unstated.',[['modules','points','tables']]),('network_architecture','Controls diagrams state communication links to BAS but no final network schedule is inferred.',[['modules','controls_context','network_architecture']]),('sequences_and_diagrams','Chilled-water, heating-water, AHU, VAV and exhaust sequences are retained as bounded source clauses.',[['modules','controls_context','sequence_inventory']]),('space_sensors_and_zones','Diagram symbols identify temperature, humidity, flow, pressure, VFD and damper control contexts without counts.',[['modules','controls_context','sensors_and_control_symbol_context']]),('source_limitations_and_conflicts','Network, field-device, physical-count and standalone-schedule limitations are explicit.',[['modules','supporting_evidence','source_limitations']]),('all_page_visual_review','Every page has a Poppler full-page review render.',[['page_review']]),('independent_corroboration','All retained rows and assertions are independently rechecked against MuPDF and Poppler.',[['module_source_sha256']])]
 return [{'id':i,'result':'reviewed_with_source_limitations_recorded','finding':f,'evidence':e} for i,f,e in ds]
def main():
 r=pages()
 put('metadata',{'document_id':IDENT,'module_role':'Cover facts and full visual ledger.','tables':[],'project':{'project_name_as_printed':'ORANGE COUNTY PUBLIC SAFETY BUILDING','location_as_printed':'BLOOMSBURY ROAD ORANGE, VA 22960','issue_as_printed':'08/03/2018','assertion_ids':['cover-project','cover-location']},'scale_semantics':{'stated_scale_records':[],'graphic_scale_bar_status':'No global scale is asserted.','takeoff_scale_status':'No plan-derived quantity is asserted.'},'visual_review_pages':r,'assertions':[a('cover-project',1,[990,80,1360,140],'ORANGE COUNTY'),a('cover-location',1,[970,245,1370,345],'BLOOMSBURY ROAD ORANGE, VA 22960')]})
 put('schedules',{'document_id':IDENT,'module_role':'Literal schedule evidence.','tables':[table('P-201-BOOSTER-PUMP',30,'P-201','DOMESTIC WATER BOOSTER PUMP SCHEDULE',100,2500,[[1200,1240]],['BP-1 GRUNDFOS CRE MULTI-E 10-3 HYDRO WATER PACKAGED, 2-PUMP BOOSTER VARIABLE DOMESTIC SYSTEM SPEED 3 100 50 25 60 3550 3 460 / 3 / 60 14 8.96 GALLON ACCEPTANCE GALLON TANK'])],'assertions':[]})
 put('points',{'document_id':IDENT,'module_role':'Literal published chilled-water control-diagram I/O row.','tables':[table('M701-CHWP-IO',52,'M-701','CHILLED WATER SYSTEM CONTROL DIAGRAM',225,1000,[[735,765]],['48 CHEMICAL FEEDER START/STOP DO HOA 2 VFD'])],'assertions':[]})
 put('point_applications',{'document_id':IDENT,'module_role':'Published control-diagram source-row scope only.','tables':[],'ledger_mode':'literal_source_row_matrices_v1','applications':[{'id':'m701-chwp-io','source_table':'M701-CHWP-IO','ownership_scope':'Published diagram I/O context only; final device owner, controller/card/terminal, address and field wiring are not stated.'}],'expanded_template_counts':{'source_rows':1,'total':1},'expanded_count_warning':'One literal diagram row is not a count of installed I/O, VFDs, pumps, controllers, terminals or cables.'})
 cs=[a('m701-sequence',52,[140,915,700,950],'CHILLED WATER SYSTEM SEQUENCE OF OPERATION'),a('m701-chiller-setpoint',52,[780,1110,1360,1140],'THE UNIT MOUNTED CHILLER CONTROLS SHALL MODULATE THE CHILLER CAPACITY TO MAINTAIN 44 DEG F CHILLED WATER'),a('m702-sequence',53,[190,1080,710,1120],'HEATING WATER SYSTEM SEQUENCE OF OPERATION'),a('m702-bacnet',53,[190,1130,760,1160],'THE HEATING WATER SYSTEM SHALL BE CONTROLLED BY A DIRECT DIGITAL PLANT CONTROLLER CONNECTED TO THE BAS.'),a('m703-ahu',54,[145,850,420,890],'SEQUENCE OF OPERATION'),a('m703-optimum-start',54,[1335,1375,1900,1410],'PROVIDE OPTIMUM START CONTROLS.'),a('m704-vav',55,[200,615,555,650],'VAV BOX SEQUENCE OF OPERATION'),a('m704-exhaust',55,[935,1300,1555,1340],'THE EXHAUST FAN SHALL OPERATE BASED UPON THE BUILDING OCCUPIED SCHEDULE'),a('m705-exhaust',56,[935,1420,1450,1460],'AS PROVIDED BY THE OWNER. WHEN SCHEDULED ON, THE EXHAUST FAN SHALL BE ENERGIZED.')]
 put('controls_context',{'document_id':IDENT,'module_role':'M-701–M-705 source-bounded control diagrams and sequences.','tables':[],'assertions':cs,'network_architecture':{'published_integration':['Chilled-water and heating-water diagrams show communication links to BAS; the heating-water sequence calls for a direct digital plant controller connected to the BAS.'],'assertion_ids':['m702-bacnet'],'boundary':'No final BACnet topology, addresses, object list, controller/card/terminal schedule, wiring/termination schedule or installed-controller total is published.'},'sequence_inventory':[{'id':'chilled-water','sheet':'M-701','assertion_ids':['m701-sequence','m701-chiller-setpoint']},{'id':'heating-water','sheet':'M-702','assertion_ids':['m702-sequence','m702-bacnet']},{'id':'ahu','sheet':'M-703','assertion_ids':['m703-ahu','m703-optimum-start']},{'id':'vav-and-exhaust','sheet':'M-704/M-705','assertion_ids':['m704-vav','m704-exhaust','m705-exhaust']}],'sensors_and_control_symbol_context':{'published_context':'Control diagrams depict temperature, humidity, pressure, flow, VFD, damper and relay function contexts.','assertion_ids':['m701-chiller-setpoint','m702-bacnet'],'boundary':'No device or zone count is derived.'}})
 put('equipment_reconciliation',{'document_id':IDENT,'module_role':'Literal schedule-row boundary.','tables':[],'ledger_mode':'literal_schedule_rows_v1','schedule_counts':{'tables':1,'rows':1,'interpretation':'One literal booster-pump schedule row, not an inferred installation total.'},'control_valve_and_damper_schedule_status':{'control_valve_schedule':'Control-valve functions appear in diagrams; this record does not claim a standalone control-valve schedule.','damper_actuator_schedule':'Damper functions appear in diagrams; this record does not claim a standalone damper-actuator schedule.'},'source_boundary':'No physical BAS takeoff is inferred.'})
 put('supporting_evidence',{'document_id':IDENT,'module_role':'Explicit retained-scope and source limits.','tables':[],'source_limitations':['All 128 pages are visually reviewed. Retained evidence is limited to one literal schedule row, one literal diagram I/O row and bounded M-701–M-705 sequence clauses.','The diagrams do not establish final field-device ownership, installed quantities, controller hardware, addressing, wiring or a point database.','No global drawing scale or plan quantity is claimed.']})
 put('document_manifest',{'id':IDENT,'rank':27,'title':'Orange County Public Safety Building','source_pdf':'pdf/27__vol1__21__Orange_County_Public_Safety_Building.pdf','source_sha256':'e47047c7322d16d44854dd5aa738f3d76087cc47f446927b00d8afc04a128f65','page_count':128,'review_status':'complete_with_documented_source_limitations','scope':'Complete 128-page visual review with bounded chilled-water/heating-water/AHU/VAV/exhaust control evidence and explicit non-inference limits.','reading_notes':['M-701/M-702 are deep plant control/sequence sources.','M-703–M-705 retain AHU, VAV and exhaust control diagrams.'],'verification_semantics':'Every retained row/assertion is rechecked against MuPDF and Poppler; no physical takeoff is inferred.','module_order':['metadata','schedules','points','controls_context','equipment_reconciliation','point_applications','supporting_evidence'],'module_sources':{k:[k] for k in ['metadata','schedules','points','controls_context','equipment_reconciliation','point_applications','supporting_evidence']},'requirement_audit':audit(),'page_review':[{'page':p['page'],'review_status':'complete','render':p['render'],'finding':p['finding']} for p in r],'declared_checks':[{'id':'pages','path':['page_review'],'operation':'length','expected':128}],'completion_checks':{'all_128_pages_visually_reviewed':True,'all_authoring_modules_dual_engine_verified_at_build':True,'source_limitations_explicit':True,'required_objectives_covered':True}})
if __name__=='__main__':main()
