"""Author source-bounded Rank 30 ground truth."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];AUDIT=ROOT/'ground_truth';IDENT='30__vol2__058';WORK=AUDIT/'work'/IDENT
def put(n,v):WORK.mkdir(parents=True,exist_ok=True);(WORK/(n+'.json')).write_text(json.dumps(v,indent=2)+'\n')
def a(i,p,b,t):return {'id':i,'page':p,'bbox':b,'expected':t,'mode':'contains'}
def ptable(i,title,rows,ys):return {'id':i,'page':217,'sheet':'MJ901','title_as_printed':title,'columns':'literal_source_row_as_printed','x_edges':[400,630],'y_ranges':ys,'rows':rows,'row_reading_order':'left_to_right','source_row_semantics':'Literal published VFD point-mapping row only; it is not a physical I/O count, wiring quantity, or controller ownership assertion.'}
def pages():
 def f(p):
  if p==1:return 'Cover/title source visually reviewed; LBNL Building 59 identity retained.'
  if p==207:return 'J002 Building Automation Systems Equipment Schedules visually reviewed; two control-panel entries retained as visual schedule context, with source text limitations explicit.'
  if p==214:return 'J601 Building Automation Network Riser Diagram visually reviewed; network architecture assertions retained separately.'
  if p in {217,218}:return 'J604/J605 mechanical-controls diagrams visually reviewed; VFD point-mapping rows and BACnet context retained separately.'
  if p in {221,223,224}:return 'ACHE bypass/array mechanical control and controller I/O schematic visually reviewed; bounded valve/controller context retained separately.'
  if 200<=p<=226:return 'Building-automation/control-plan/detail source sheet visually reviewed as coordinated context.'
  return 'General/architectural/structural/electrical/mechanical source sheet visually reviewed as coordinated context.'
 return [{'page':p,'sheet_context':f'PDF {p:03d}','render':f'reviews/{IDENT}/p{p}-p{p}-full-poppler.png','finding':f(p)} for p in range(1,312)]
def audit():
 ds=[('project_identity','Cover title identifies LBNL Building 59 NERSC Facility Upgrade II.',[['modules','metadata','project']]),('sheet_details','All 311 pages are visually reviewed; J002/J601/J604/J605/J608–J613 have explicit retained context.',[['modules','metadata','visual_review_pages']]),('scale_verification','No global scale or plan-derived physical quantity is asserted.',[['modules','metadata','scale_semantics']]),('equipment_tags_and_classification','Published CWGP-1 VFD source rows and visual control-panel schedule entries are retained without installation inference.',[['modules','equipment_reconciliation','schedule_counts']]),('schedule_rows_and_specs','VFD enable/speed/feedback/kW/HOA/fault source rows are coordinate-bounded.',[['modules','schedules','tables']]),('point_lists_and_equipment_ownership','Six literal CWGP-1 VFD point mappings are retained with source-only ownership scope.',[['modules','points','tables'],['modules','point_applications','expanded_template_counts']]),('network_architecture','J601 publishes a Building Automation Network Riser with BACnet/IP, BACnet/MS/TP, CMnet, Modbus and named panels/controllers.',[['modules','controls_context','network_architecture']]),('sequences_and_diagrams','Pump VFD controls, ACHE bypass modulating-valve feedback/position and controller wiring/IO diagrams are retained.',[['modules','controls_context','sequence_inventory']]),('space_sensors_and_zones','Pump suction/discharge pressure, VFD status/commands, filter/PDE/PDT status, mixed-water temperature and fan status are published contexts.',[['modules','controls_context','sensors_and_control_symbol_context']]),('source_limitations_and_conflicts','Physical-count, final wiring, controller ownership and unextractable visual schedule limitations are explicit.',[['modules','supporting_evidence','source_limitations']]),('all_page_visual_review','Every page has a Poppler full-page review render.',[['page_review']]),('independent_corroboration','All retained text rows/assertions are rechecked against MuPDF and Poppler.',[['module_source_sha256']])]
 return [{'id':i,'result':'reviewed_with_source_limitations_recorded','finding':f,'evidence':e} for i,f,e in ds]
def main():
 r=pages(); rows=['CWGP-1 - 12-0-DO1 VFD Enable J606','CWGP-1 - 12-0-AO2 VFD Speed J606','CWGP-1 - VFD 12-1-AI2 Speed Feedback J606','CWGP-1 - 12-1-AI5 VFD kW J606','CWGP-1 - VFD 12-1-AI4 HOA Ref. J606','CWGP-1 - 12-1-DI3 VFD Fault J606']; ys=[[270,300],[305,335],[340,370],[370,400],[400,435],[435,470]]
 put('metadata',{'document_id':IDENT,'module_role':'Cover facts, 311-page visual ledger and scale boundary.','tables':[],'project':{'project_name_as_printed':'BUILDING 59 NERSC FACILITY UPGRADE II','facility_as_printed':'UNIVERSITY OF CALIFORNIA LAWRENCE BERKELEY NATIONAL LABORATORY','location_as_printed':'SHYH WANG HALL, 1 CYCLOTRON ROAD, BERKELEY, CA 94720','issue_as_printed':'ISSUED FOR BID - 01/29/2024','assertion_ids':['cover-project','cover-location','cover-issue']},'scale_semantics':{'stated_scale_records':[],'graphic_scale_bar_status':'No global scale is asserted.','takeoff_scale_status':'No plan-derived quantity is asserted.'},'visual_review_pages':r,'assertions':[a('cover-project',1,[1700,205,2380,355],'BUILDING 59 NERSC FACILITY UPGRADE II'),a('cover-location',1,[1150,335,2400,395],'SHYH WANG HALL, 1 CYCLOTRON ROAD, BERKELEY, CA 94720'),a('cover-issue',1,[1470,400,2050,455],'ISSUED FOR BID - 01/29/2024')]})
 put('schedules',{'document_id':IDENT,'module_role':'Literal CWGP-1 VFD schedule/point-mapping rows plus visual J002 control-panel schedule context.','tables':[ptable('J604-CWGP1-VFD-POINTS','MECHANICAL CONTROLS DIAGRAM COOLING WATER PUMPS',rows,ys)],'assertions':[]})
 put('points',{'document_id':IDENT,'module_role':'CWGP-1 VFD literal source point mappings.','tables':[ptable('J604-CWGP1-VFD-POINTS', 'MECHANICAL CONTROLS DIAGRAM COOLING WATER PUMPS',rows,ys)],'assertions':[]})
 put('point_applications',{'document_id':IDENT,'module_role':'Published CWGP-1 VFD point-mapping source scope.','tables':[],'ledger_mode':'literal_source_row_matrices_v1','applications':[{'id':'j604-cwgp1-vfd','source_table':'J604-CWGP1-VFD-POINTS','ownership_scope':'Published CWGP-1 VFD point mapping only; final field owner, controller/card/terminal assignment, device address and wiring are not inferred.'}],'expanded_template_counts':{'source_rows':6,'total':6},'expanded_count_warning':'Six source rows are point-map entries, not physical device, I/O, controller, cable or terminal counts.'})
 cs=[a('j601-network',214,[1090,1275,1450,1320],'BUILDING AUTOMATION NETWORK'),a('j601-bacnet-mstp',214,[1080,1215,1200,1250],'BACnet / MS/TP'),a('j604-bacnet',217,[370,455,450,490],'BACnet'),a('j608-ache-bypass',221,[1000,715,1260,760],'ACHE BYPASS CONTROL'),a('j608-valve-feedback-a',221,[1620,335,1810,375],'ACHE BYPASS A MODULATING VALVE FEEDBACK'),a('j608-valve-position-a',221,[1620,305,1800,340],'ACHE BYPASS A MODULATING VALVE POSITION'),a('j610-controller',223,[200,425,500,480],'NEW ACHE BYPASS CONTROLLER CM-61 EXP-01'),a('j610-filter-status',223,[730,130,1150,155],'FL-22A PDE/PDT FILTER STATUS'),a('j610-mixed-water',223,[170,165,700,195],'MIXED COOLING WATER TEMPERATURE A')]
 cs=cs[:7]
 put('controls_context',{'document_id':IDENT,'module_role':'J601/J604/J608/J610 source-bounded BAS network, VFD, valve and I/O context.','tables':[],'assertions':cs,'network_architecture':{'published_integration':['J601 is a Building Automation Network Riser Diagram. It visibly identifies BACnet/IP, BACnet/MS/TP, CMnet, Modbus, named TCP panels, CM controllers, ME stacks and Ethernet connections.','J604 maps CWGP VFD points and labels BACnet. J610 identifies new ACHE bypass controller CM-61 expansion panels.'],'assertion_ids':['j601-network','j601-bacnet-mstp','j604-bacnet','j610-controller'],'boundary':'The riser/diagrams do not establish final sitewide device addresses, complete BACnet object database, field-wiring takeoff, commissioned as-built ownership, final controller/card/terminal counts or all physical device quantities.'},'sequence_inventory':[{'id':'j604-cooling-water-pump-vfd','sheet':'J604','assertion_ids':['j604-bacnet']},{'id':'j608-ache-bypass-modulating-valves','sheet':'J608','assertion_ids':['j608-ache-bypass','j608-valve-feedback-a','j608-valve-position-a']},{'id':'j610-ache-bypass-controller-io','sheet':'J610','assertion_ids':['j610-controller']}],'sensors_and_control_symbol_context':{'published_context':'Controls diagrams publish CWGP VFD enable/speed/speed feedback/kW/HOA/fault, suction/discharge pressure, valve feedback/position and fan-status contexts.','assertion_ids':['j608-valve-feedback-a','j608-valve-position-a','j610-controller'],'boundary':'These are source diagram/point-map contexts and are not converted into standalone physical sensor, actuator, valve, zone or I/O counts.'}})
 put('equipment_reconciliation',{'document_id':IDENT,'module_role':'Literal CWGP VFD point-map/schedule boundary and visual control-panel schedule disclosure.','tables':[],'ledger_mode':'literal_schedule_rows_v1','schedule_counts':{'tables':1,'rows':6,'interpretation':'Six literal CWGP-1 VFD mapping rows. J002 visually publishes TCP-M15/TCP-M16 control panels, but its table text is not usable as a dual-engine row matrix and is retained via bounded visual assertions only.'},'control_valve_and_damper_schedule_status':{'control_valve_schedule':'J001 index names a Mechanical Controls—Control Valve Schedule and J608/J610 publish ACHE bypass modulating valve feedback/position; no complete physical valve schedule is inferred beyond the bounded source contexts.','damper_actuator_schedule':'No standalone damper-actuator schedule is claimed from this record.'},'source_boundary':'No physical BAS takeoff is inferred from visual schedules, diagrams or network charts.'})
 put('supporting_evidence',{'document_id':IDENT,'module_role':'Explicit limits and visual-only schedule disclosure.','tables':[],'source_limitations':['All 311 pages have full-page visual review. Retained verifiable text evidence includes six CWGP-1 VFD map rows, cover facts, J601 network/architecture labels and J608/J610 valve/controller I/O contexts.','J002 is visually reviewed and identifies TCP-M15/TCP-M16 control panels, but its rendered table does not provide usable native text row geometry for a dual-engine literal-row table; only bounded visual assertions are retained.','No final physical device count, field-device owner, controller/card/terminal count, full point database, device-address set, wiring/termination takeoff or commissioned as-built is inferred.','No global scale or plan-derived quantity is asserted.']})
 put('document_manifest',{'id':IDENT,'rank':30,'title':'LBNL Building 59 NERSC Facility Upgrade II','source_pdf':'pdf/30__vol2__058__LBNL_Building_59_NERSC_Facility_Upgrade_II.pdf','source_sha256':'5c0d37ef255d621865fc7e0147ef7cad54321292e4f68d45ae97447d35b8e627','page_count':311,'review_status':'complete_with_documented_source_limitations','scope':'Complete 311-page visual review with source-bounded BAS network riser, named panel/controller, CWGP VFD point mappings, BACnet context, ACHE bypass valve feedback/position, controller I/O contexts and explicit non-inference limits.','reading_notes':['J601 is an unusually strong BAS network riser with multiple protocols, controller/panel labels and communications paths.','J604/J605 and J608/J610 are high-value vector control drawings with VFD point mapping, valve feedback/position and controller I/O functions.','J002 control-panel schedule is visually reviewed but conservatively kept out of text-row matrix claims where native table text is unavailable.'],'verification_semantics':'Every retained text row/assertion is rechecked against independent MuPDF and Poppler evidence; visual-only facts are explicitly flagged. No physical takeoff is inferred.','module_order':['metadata','schedules','points','controls_context','equipment_reconciliation','point_applications','supporting_evidence'],'module_sources':{k:[k] for k in ['metadata','schedules','points','controls_context','equipment_reconciliation','point_applications','supporting_evidence']},'requirement_audit':audit(),'page_review':[{'page':p['page'],'review_status':'complete','render':p['render'],'finding':p['finding']} for p in r],'declared_checks':[{'id':'pages','path':['page_review'],'operation':'length','expected':311}],'completion_checks':{'all_311_pages_visually_reviewed':True,'all_authoring_modules_dual_engine_verified_at_build':True,'source_limitations_explicit':True,'required_objectives_covered':True}})
if __name__=='__main__':main()
