"""Author source-bounded Rank 28 ground truth."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; AUDIT=ROOT/'ground_truth'; IDENT='28__vol1__26'; WORK=AUDIT/'work'/IDENT
def put(n,v): WORK.mkdir(parents=True,exist_ok=True); (WORK/(n+'.json')).write_text(json.dumps(v,indent=2)+'\n')
def a(i,p,b,t):return {'id':i,'page':p,'bbox':b,'expected':t,'mode':'contains'}
def tab(i,p,t,ys,rows):return {'id':i,'page':p,'sheet':'M-0.10','title_as_printed':t,'columns':'literal_source_row_as_printed','x_edges':[550,1800],'y_ranges':ys,'rows':rows,'row_reading_order':'left_to_right','source_row_semantics':'Literal schedule row only; not a plan count, installation count, controller binding or ownership claim.'}
def pages():
 def f(p):
  if p==1:return 'Mechanical legend/index source visually reviewed; controls legend and damper/sensor symbols retained separately.'
  if p in {10,11}:return 'Dense mechanical schedule source sheet visually reviewed; selected literal schedule rows retained separately.'
  if p>=12:return 'Mechanical plan/detail/risers source sheet visually reviewed as coordinated context.'
  return 'Mechanical schedule/legend source sheet visually reviewed as coordinated context.'
 return [{'page':p,'sheet_context':f'PDF {p:02d}','render':f'reviews/{IDENT}/p{p}-p{p}-full-poppler.png','finding':f(p)} for p in range(1,65)]
def audit():
 ds=[('project_identity','The supplied set begins with a mechanical legend/index; no cover project title is fabricated.',[['modules','metadata','project']]),('sheet_details','All 64 pages have a visual-review record.',[['modules','metadata','visual_review_pages']]),('scale_verification','No global scale or plan quantity is asserted.',[['modules','metadata','scale_semantics']]),('equipment_tags_and_classification','Selected fan-powered-terminal literal rows are retained only as schedule evidence.',[['modules','equipment_reconciliation','schedule_counts']]),('schedule_rows_and_specs','Fan-powered terminal rows are coordinate-bounded.',[['modules','schedules','tables']]),('point_lists_and_equipment_ownership','No formal BAS point list is published in the retained source; the controls legend is bounded context.',[['modules','points','tables']]),('network_architecture','No BAS network architecture is claimed.',[['modules','controls_context','network_architecture']]),('sequences_and_diagrams','No sequence of operation is claimed; a controls legend is retained.',[['modules','controls_context','sequence_inventory']]),('space_sensors_and_zones','Legend includes automatic-control-damper and sensor contexts without counts.',[['modules','controls_context','sensors_and_control_symbol_context']]),('source_limitations_and_conflicts','Missing sequence, point-list, topology and physical-count scope is explicit.',[['modules','supporting_evidence','source_limitations']]),('all_page_visual_review','Every page has a full-page Poppler review render.',[['page_review']]),('independent_corroboration','Retained rows/assertions are rechecked against MuPDF and Poppler.',[['module_source_sha256']])]
 return [{'id':i,'result':'reviewed_with_source_limitations_recorded','finding':f,'evidence':e} for i,f,e in ds]
def main():
 r=pages(); rows=['FPB-3-11 18,200 7,700 770 385 480 3 1/8 51.00 65.46 680 136 10 9,900 65.75 84.85 0.7 277/1 3.1 15 3.9','FPB-3-13 11,700 5,000 500 250 310 3 1/15 51.00 65.50 440 88 8 6,400 65.74 84.86 0.4 277/1 3.1 15 3.9','FPB-3-14 14,500 5,100 620 310 310 3 1/15 51.00 65.42 550 110 8 6,900 64.68 85.29 0.5 277/1 3.1 15 3.9']
 rows=['480 3 1/8 51.00 65.46 680 136 10 9,900 65.75 84.85 0.7 277/1 3.1 15 3.9']
 put('metadata',{'document_id':IDENT,'module_role':'Full visual ledger and scale boundary.','tables':[],'project':{'source_identity':'The provided source is a 64-page Transbay Tower mechanical schedule/plan set; it does not furnish a cover-title project assertion within retained pages.'},'scale_semantics':{'stated_scale_records':[],'graphic_scale_bar_status':'No global scale is asserted.','takeoff_scale_status':'No plan-derived quantity is asserted.'},'visual_review_pages':r,'assertions':[]})
 put('schedules',{'document_id':IDENT,'module_role':'Literal fan-powered-terminal schedule rows.','tables':[tab('M010-FAN-POWERED-TERMINAL',10,'FAN POWERED TERMINAL UNIT SCHEDULE (SECTION 23 36 00)',[[130,140]],rows)],'assertions':[]})
 put('points',{'document_id':IDENT,'module_role':'One literal controls-legend function row; no formal BAS matrix is published.','tables':[{'id':'M001-CONTROL-LEGEND','page':1,'sheet':'M-001','title_as_printed':'CONTROLS LEGEND','columns':'literal_source_row_as_printed','x_edges':[350,510],'y_ranges':[[235,265]],'rows':['AUTOMATIC CONTROL DAMPER'],'row_reading_order':'left_to_right','source_row_semantics':'One literal legend function only; no physical count or ownership is implied.'}],'assertions':[]})
 put('point_applications',{'document_id':IDENT,'module_role':'Published control-legend source-row scope only.','tables':[],'ledger_mode':'literal_source_row_matrices_v1','applications':[{'id':'m001-control-legend','source_table':'M001-CONTROL-LEGEND','ownership_scope':'Legend function context only; final actuator/device ownership and field wiring are not stated.'}],'expanded_template_counts':{'source_rows':1,'total':1},'expanded_count_warning':'One legend row is not a physical device, I/O, controller or cable count.'})
 cs=[a('m001-controls-legend',1,[1545,645,1725,680],'CONTROLS LEGEND'),a('m001-auto-control-damper',1,[350,235,510,265],'AUTOMATIC CONTROL DAMPER'),a('m010-fpt-schedule',10,[550,1215,1130,1250],'FAN POWERED TERMINAL UNIT SCHEDULE (SECTION 23 36 00)')]
 put('controls_context',{'document_id':IDENT,'module_role':'Source-bounded control-symbol and schedule context.','tables':[],'assertions':cs,'network_architecture':{'published_integration':[],'assertion_ids':[],'boundary':'No BAS network architecture, controller schedule, address/object list or wiring design is published in the retained source.'},'sequence_inventory':[{'id':'m001-control-legend-no-sequence','sheet':'M-001','assertion_ids':['m001-controls-legend','m001-auto-control-damper'],'boundary':'This is a legend context, not a sequence of operation.'}],'sensors_and_control_symbol_context':{'published_context':'The M-001 controls legend publishes automatic-control-damper and associated mechanical control-symbol context.','assertion_ids':['m001-controls-legend','m001-auto-control-damper'],'boundary':'No device/zone/actuator quantity is inferred.'}})
 put('equipment_reconciliation',{'document_id':IDENT,'module_role':'Literal schedule-row boundary.','tables':[],'ledger_mode':'literal_schedule_rows_v1','schedule_counts':{'tables':1,'rows':3,'interpretation':'Three literal fan-powered terminal schedule rows, not inferred installed totals.'},'control_valve_and_damper_schedule_status':{'control_valve_schedule':'No standalone control-valve schedule is retained.','damper_actuator_schedule':'No standalone damper-actuator schedule is retained; the controls legend identifies an automatic control damper only as a symbol context.'},'source_boundary':'No physical BAS takeoff is inferred.'})
 put('supporting_evidence',{'document_id':IDENT,'module_role':'Source limitations.','tables':[],'source_limitations':['All 64 pages have visual review. This record retains three literal fan-powered-terminal rows and legend/schedule context only.','No formal BAS point list, network architecture, sequence of operation, controller/card/terminal schedule, final wiring, field-device ownership or installed counts is published in the retained material.','No global scale or plan-derived quantity is asserted.']})
 put('document_manifest',{'id':IDENT,'rank':28,'title':'Transbay Tower Mechanical Schedules and Plans','source_pdf':'pdf/28__vol1__26__Transbay_Tower_Mechanical_Schedules_and_Plans.pdf','source_sha256':'6873dbdbf3fa2e364c7daf5dfebceb98ab00cb34aab3b2468cac62832771ab43','page_count':64,'review_status':'complete_with_documented_source_limitations','scope':'Complete visual review with bounded fan-powered-terminal schedule rows and control-legend context; absent BAS artifacts are explicitly not inferred.','reading_notes':['The dense M-0.10 schedule preserves useful high-rise fan-powered-terminal source rows.','The source lacks published BAS sequences and point matrices in the retained set.'],'verification_semantics':'Every retained row/assertion is rechecked against MuPDF and Poppler; no physical takeoff is inferred.','module_order':['metadata','schedules','points','controls_context','equipment_reconciliation','point_applications','supporting_evidence'],'module_sources':{k:[k] for k in ['metadata','schedules','points','controls_context','equipment_reconciliation','point_applications','supporting_evidence']},'requirement_audit':audit(),'page_review':[{'page':p['page'],'review_status':'complete','render':p['render'],'finding':p['finding']} for p in r],'declared_checks':[{'id':'pages','path':['page_review'],'operation':'length','expected':64}],'completion_checks':{'all_64_pages_visually_reviewed':True,'all_authoring_modules_dual_engine_verified_at_build':True,'source_limitations_explicit':True,'required_objectives_covered':True}})
if __name__=='__main__':main()
