"""Bounded M-501 sequence and controls context for rank 07."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
AUDIT = ROOT / "ground_truth"
IDENT = "07__vol2__061"
OUT = AUDIT / "work" / IDENT / "controls_sequences.json"


def a(id_, bbox, expected):
    return {"id": id_, "page": 56, "bbox": bbox, "expected": expected, "mode": "exact"}


def main():
    assertions = [
        a("m501-exhaust-n1", [190, 1118, 1100, 1143], "a. FANS EF-3 AND EF-2 SHALL OPERATE IN A N-1 ARRANGEMENT AND BOTH FANS SHALL RUN SIMULTANEOUSLY."),
        a("m501-heat-recovery-modes", [180, 1415, 700, 1448], "1. THE HEAT RECOVERY SYSTEM CONSISTS OF THREE MODES: a. HEAT PUMP BYPASS (DEFAULT) b. HEAT PUMP"),
        a("m501-heat-recovery-lead-standby", [180, 1468, 700, 1510], "a. THE PUMPS SHALL OPERATE IN A LEAD, STANDBY MODE, WITH THE LEAD PUMP SWITCHING ONCE PER WEEK. b. UPON FAILURE OF THE LEAD PUMP, THE STANDBY PUMP SHALL BE STARTED AND AN ALARM SENT. c. VARIABLE FREQUENCY DRIVE CONTROL"),
        a("m501-heat-recovery-bypass", [180, 1574, 700, 1630], "a. HEAT PUMP BYPASS MODE SHALL BE INITIATED WHEN ANY OF THE FOLLOWING OCCUR: • HEAT PUMP IS ENABLED BUT STATUS IS OFF. • HEAT PUMP IS DISABLED BUT STATUS IS ON. • CONDENSER LEAVING WATER TEMPERATURE (TTE-14) IS BELOW THE CONDENSER LEAVING WATER TEMPERATURE LOW LIMIT SETPOINT OF 35 DEG. F. (ADJ.) FOR MORE THAN 5 MINUTES."),
        a("m501-heat-recovery-heat-pump", [180, 1685, 700, 1720], "a. HEAT PUMP MODE SHALL BE INITIATED WHEN ANY OF THE FOLLOWING OCCUR: • CONDENSER LEAVING WATER TEMPERATURE (TTE-14) IS ABOVE THE CONDENSER LEAVING WATER TEMPERATURE LOW LIMIT SETPOINT."),
        a("m501-ahu-occupancy", [1200, 890, 2000, 925], "A. THE AIR HANDLING UNIT DOES NOT HAVE OCCUPANCY MODES AND SHALL RUN AT ALL TIMES TO PROVIDE MAKEUP AIR TO LABORARTORY SPACES. INDIVIDUAL ZONES SHALL HAVE THE ABILITY TO SET-UP AND SET-BACK TEMPERATURE SET POINTS BASED ON OCCUPANCY. REFER TO VARIABLE AIR VOLUME UNIT SEQUENCE OF OPERATIONS."),
        a("m501-ahu-supply-array", [1200, 960, 2000, 1015], "A. ANY SEQUENCE OF OPERATION DESCRIBED HEREIN STARTING OR STOPPING THE FAN(S) SHALL SLOWLY RAMP UP/DOWN THE FAN(S) AT APPROXIMATELY 1 HZ/SECOND. B. START/STOP: 1. FANS SHALL RUN THROUGHOUT ALL MODES OF OPERATION AND A MINIMUM OF ONE FAN SHALL RUN AT ALL TIMES. C. THE SUPPLY ARRAY CONSISTS OF SIX FANS. THE FANS SHALL START AND STOP TO EQUALIZE RUNTIME. THE RUNTIME VARIABLE SHALL BE A MANUALLY"),
        a("m501-ahu-static-pressure", [1200, 1110, 2000, 1195], "D. STATIC PRESSURE SET-POINT 1. SUPPLY FAN ARRAY SHALL UTILIZE TWO STATIC PRESSURE SENSORS. SUPPLY FAN ARRAY SHALL MAINTAIN THE HIGHEST OF TWO STATIC PRESSURE SENSORS. 2. ACTIVE SUPPLY DUCT STATIC PRESSURE SETPOINT SHALL UTILIZE A TRIM AND RESPONSE PRESSURE RESET SCHEME EQUAL TO THE FOLLOWING: a. INITIAL LOW LIMIT FOR DUCT STATIC PRESSURE SETPOINT SHALL BE 1.0 IN. W.C. (ADJ.). LOW LIMIT SHALL BE DETERMINED DURING TESTING AND BALANCING. b. INITIAL HIGH LIMIT FOR THE DUCT STATIC PRESSURE SETPOINT SHALL BE 3.0 IN. W.C. (ADJ.). HIGH LIMIT SHALL BE DETERMINED DURING TESTING AND BALANCING."),
        a("m501-ahu-cooling", [2000, 925, 2800, 995], "BID ALTERNATE #1: B. THE HEAT RECOVERY COIL SHALL BE THE SECOND STAGE OF COOLING. REFER TO HEAT RECOVERY SYSTEM DIAGRAM FOR SEQUENCE OF OPERATION. C. THE CHILLED WATER COIL SHALL BE THE SECOND STAGE OF COOLING. 1. WHEN THERE IS A CALL FOR SECOND STAGE OF COOLING, MODULATE THE CHILLED WATER VALVES (V-3 AND V-4) IN TANDEM TO MAINTAIN THE ACTIVE DISCHARGE AIR TEMPERATURE SETPONT. D. HEATING"),
        a("m501-ahu-heating", [2000, 1008, 2800, 1060], "2. THE HEAT RECOVERY COIL SHALL BE THE FIRST STAGE OF HEATING. REFER TO HEAT RECOVERY SYSTEM DIAGRAM FOR SEQUENCE OF OPERATION. 3. WHEN THERE IS A CALL FOR A SECOND STAGE OF HEATING, THE HEATING HOT WATER CONTROL VALVE (V-2) SHALL BE MODULATED TO MAINTAIN THE ACTIVE SUPPLY AIR TEMPERATURE SETPOINT."),
        a("m501-ahu-humidifier", [2000, 1080, 2800, 1170], "A. OCCUPIED MODE 1. BAS SHALL ENABLE HUMIDIFIER OPERATION WHEN THE FOLLOWING OCCURS: a. OUTDOOR AIR TEMPERATURES ARE BELOW 35 DEG. F. (ADJ.) AND b. RETURN AIR RELATIVE HUMIDITY (HTE-1) FALLS BELOW THE ACTIVE RELATIVE HUMIDITY SETPOINT OF 30% RH (ADJ.) OR c. HUMIDIFIER IS MANUALLY SET TO OPERATE VIA REMOTE WORKSTATION. 2. BAS SHALL SEND MODULATING SIGNAL TO HUM-15 TO MAINTAIN ACTIVE RETURN AIR RELATIVE HUMIDITY SETPOINT OF 40% RH (ADJ.). 3. UPON PROOF OF FLOW VIA FLOW SWITCH (FS-1), BAS SHALL MODULATE STEAM VALVE (V-1) TO MAINTAIN ACTIVE RETURN AIR RELATIVE HUMIDITY SETPOINT."),
        a("m501-ahu-safety", [2000, 1190, 2800, 1320], "A. ANY SAFETY CONTROLS SEQUENCES DESCRIBED HEREIN SHALL INITIATE AN ALARM. REFER TO POINTS LIST. B. RESET OF ANY SAFETY MODE SHALL RETURN AIR HANDLING UNIT TO LAST KNOWN MODE OF OPERATION. C. FAN SHUTDOWN MODE 1. FAN SHUTDOWN SAFETIES SHALL BE HARD-WIRED AND SHALL NOT DEPEND ON THE BAS SYSTEM OPERATION. 2. IF FAN SHUTDOWN MODE IS ACTIVATED THE FOLLOWING SHALL OCCUR: a. ALL SUPPLY AND RETURN FANS SHALL SHUTDOWN. b. CHILLED WATER VALVES (V-3 AND V-4) SHALL OPEN. c. HOT WATER PUMP (HWP-B) SHALL RUN. d. HOT WATER VALVE (V-2) SHALL OPEN TO N.O. POSITION. e. HUMIDIFIER VALVE (V-1) SHALL CLOSE AND HUMIDIFIER SHALL BE DISABLED. f. VENTILATION DAMPER (AE-3) SHALL CLOSE."),
        a("m501-ahu-return-array", [1200, 1330, 2000, 1400], "A. ANY SEQUENCE OF OPERATION DESCRIBED HEREIN STARTING OR STOPPING THE FAN(S) SHALL SLOWLY RAMP UP/DOWN THE FAN(S) AT APPROXIMATELY 1 HZ/SECOND. B. START/STOP: 1. FANS SHALL RUN THROUGHOUT ALL MODES OF OPERATION AND A MINIMUM OF ONE FAN SHALL RUN AT ALL TIMES. C. THE RETURN ARRAY CONSISTS OF FOUR FANS. THE FANS SHALL START AND STOP TO EQUALIZE RUNTIME. THE RUNTIME VARIABLE SHALL BE A MANUALLY RESETTABLE VARIABLE ON THE GUI. 1. WITH ONE FAN RUNNING AT 55 HZ (ADJ.) AND A FURTHER INCREASE IN RETURN AIRFLOW IS REQUIRED, START THE FAN WITH THE LOWEST RUNTIME TO ITS"),
        a("m501-ahu-dampers", [1200, 1490, 2000, 1590], "DAMPER CONTROL A. RETURN AIR DAMPER 1. RETURN DAMPER (AE-2) SHALL MODULATE TO REVERSE TRACK THE VENTILATION AND ECONOMIZER DAMPERS. B. RELIEF AIR DAMPER 1. RELIEF DAMPER (AE-1) SHALL MODULATE TO MAINTAIN PRESSURE SETPOINT IN THE RETURN FAN PLENUM (PTE-2) AT OR BELOW 0.1\" W.C. (adj.). C. ECONOMIZER DAMPER 1. IF ANY SUPPLY FAN IS PROVEN ON, DAMPER (AE-4) SHALL MODULATE FROM 0-100% OPEN FOR DISCHARGE AIR TEMPERATURE CONTROL UNLESS UNIT IS OUTSIDE OF ECONOMIZER MODE IN WHICH CASE IT SHALL BE CLOSED. REFER TO SUPPLY AIR TEMPERATURE CONTROL SEQUENCE."),
        a("m501-vav-occupied", [1700, 1733, 2050, 1760], "OCCUPIED MODE ZONE SHALL MAINTAIN THE OCCUPIED SETPOINT OF 72 DEG. F. (ADJ.) SHALL HAVE A 2 DEG. F. DEADBAND."),
        a("m501-vav-unoccupied", [1700, 1765, 2050, 1805], "UNOCCUPIED MODE ZONE SHALL MAINTAIN THE UNOCCUPIED HEATING SETPOINT OF 62 DEG. (ADJ.) AND UNOCCUPIED COOLING SETPOINT OF 80 DEG. F. (ADJ.) BYPASS MODE"),
        a("m501-vav-bypass", [1700, 1810, 2050, 1868], "ZONE SHALL INDEX TO BYPASS MODE WHEN CURRENT MODE IS UNOCCUPIED AND AN OCCUPANT PRESSES THE OVERRIDE BUTTON ON THERMOSTAT OR OCCUPANCY SENSOR SENSES OCCUPANCY. ZONE SHALL MAINTAIN THE OCCUPIED HEATING AND COOLING SETPOINTS. BYPASS MODE SHALL BE ACTIVE 1 HOUR (ADJ.) AFTER OCCUPANCY IS SENSED BEFORE RETURNING TO UNOCCUPIED MODE."),
        a("m501-vav-cooling", [2100, 1733, 2800, 1805], "ZONE TEMPERATURE CONTROL SEQUENCES SHALL BE THE THE SAME IN OCCUPIED, UNOCCUPIED, AND BYPASS MODES OF OPERATION. COOLING MODE: 1. IF THE ZONE TEMPERATURE RISES ABOVE THE ACTIVE ZONE TEMPERATURE SETPOINT BY THE TEMPERATURE DEADBAND OF 2 DEG. F. (ADJ.), THE VAV AIRFLOW SHALL VARY FROM THE MINIMUM AIRFLOW SETTING TO THE MAXIMUM AIRFLOW SETTING TO MAINTAIN ZONE TEMPERATURE."),
        a("m501-vav-heating", [2100, 1810, 2800, 1905], "HEATING MODE: 1. IF THE ZONE TEMPERATURE FALLS BELOW THE ACTIVE ZONE TEMPERATURE SETPOINT AND THE TEMPERATURE DEADBAND OF 2 DEG. F. (ADJ.), THE TAB SHALL MAINTAIN THE MINIMUM AIRFLOW SETTING AND MODULATE THE REHEAT COIL VALVE FROM 0-100%. 2. IF THE REHEAT COIL VALVE IS AT 100% AND THE ZONE TEMPERATURE CONTINUES TO FALL, THE TAB AIRFLOW SHALL VARY FROM THE MINIMUM AIRFLOW SETTING TO THE MAXIMUM HEATING AIRFLOW SETTING AS REQUIRED TO MAINTAIN ZONE TEMPERATURE."),
        a("m501-vav-safety", [2100, 1930, 2800, 1980], "SAFETY CONTROLS IF AIR HANDLING UNIT IS IN FAN SHUTDOWN MODE OF OPERATION, VAV DAMPERS SHALL CLOSE AND REHEAT COIL VALVES SHALL OPEN."),
        a("m501-hhw-description", [770, 1155, 1180, 1190], "DESCRIPTION: A. THE VARIABLE VOLUME HEATING HOT WATER PLANT CONSISTS OF TWO REDUNDANT STEAM TO HOT WATER HEAT"),
        a("m501-hhw-enable", [770, 1200, 1180, 1230], "PLANT ENABLE/DISABLE A. THE PLANT SHALL INCLUDE AN ENABLING SCHEDULE THAT ALLOWS OPERATORS TO LOCK OUT THE PLANT DURING OFF-"),
        a("m501-hhw-pumps", [770, 1350, 1180, 1430], "PUMP CONTROL A. THE PUMPS SHALL BE LEAD/STANDBY ALTERNATED. THE LEAD/STANDBY POSITIONS OF EACH PUMP SHALL SWITCH ONCE A WEEK. 1. THE STANDBY PUMP SHALL FIRST BE STARTED AND PROVEN ON BEFORE FORMER LEAD EQUIPMENT IS CHANGED TO STANDBY AND SHUT OFF."),
        a("m501-hhw-temperature-reset", [770, 1795, 1180, 1935], "A. THE HEAT EXCHANGERS SHALL BE LEAD/STANDBY ALTERNATED BY OPENING THE DEDICATED HOT WATER ISOLATION VALVE. THE LEAD/STANDBY POSITIONS OF EACH HEAT EXCHANGER SHALL SWITCH ONCE A WEEK. B. THE STEAM CONTROL VALVES SHALL MAINTAIN THE ACTIVE HEATING WATER SUPPLY TEMPERATURE SETPOINT BY GRADUALLY MODULATING THE ONE-THIRD AND TWO-THIRDS CAPACITY NORMALLY CLOSED TWO-WAY STEAM CONTROL VALVES SERVING EACH CONVERTER. a. THE ACTIVE HEATING WATER SUPPLY TEMPERATURE SETPOINT SHALL BE RESET FROM 120 DEG. F. TO 90 DEG. F. LINEARLY FROM OUTSIDE AIR TEMPERATURES OF 20 DEG. F. TO 50 DEG. F. RESPECTIVELY."),
        a("m501-hhw-safeties", [770, 1940, 1180, 2020], "SAFETIES A. PROVIDE HIGH LIMIT TEMPERATURE SWITCHES IN EACH HEAT EXCHANGER DISCHARGE LINES WHICH SHALL DE-ENERGIZE THE OPERATING PUMP AND CLOSE THE STEAM CONTROL VALVES ON TEMPERATURES EXCEEDING THE SETPOINT OF 200 DEG. F. (adj.) FOR MORE THAN 2 MINUTES (adj.). EACH HIGH LIMIT TEMPERATURE SWITCH SHALL HAVE A MANUAL RESET. B. A MANUAL RESET IN THE BAS PANEL SHALL BE PROVIDED FOR"),
    ]
    sequence_inventory = [
        {"id": "laboratory-exhaust-fans", "sheet": "M-501", "assertion_ids": ["m501-exhaust-n1"]},
        {"id": "heat-recovery-system", "sheet": "M-501", "assertion_ids": ["m501-heat-recovery-modes", "m501-heat-recovery-lead-standby", "m501-heat-recovery-bypass", "m501-heat-recovery-heat-pump"]},
        {"id": "air-handling-unit", "sheet": "M-501", "assertion_ids": ["m501-ahu-occupancy", "m501-ahu-supply-array", "m501-ahu-static-pressure", "m501-ahu-cooling", "m501-ahu-heating", "m501-ahu-humidifier", "m501-ahu-safety", "m501-ahu-return-array", "m501-ahu-dampers"]},
        {"id": "vav-zone", "sheet": "M-501", "assertion_ids": ["m501-vav-occupied", "m501-vav-unoccupied", "m501-vav-bypass", "m501-vav-cooling", "m501-vav-heating", "m501-vav-safety"]},
        {"id": "heating-hot-water-plant", "sheet": "M-501", "assertion_ids": ["m501-hhw-description", "m501-hhw-enable", "m501-hhw-pumps", "m501-hhw-temperature-reset", "m501-hhw-safeties"]},
    ]
    data = {
        "document_id": IDENT,
        "module_role": "Source-bounded M-501 operating-sequence clauses for the bid-alternate laboratory exhaust/heat-recovery system, custom AHU, VAV zones and heating-hot-water plant.",
        "tables": [], "assertions": assertions,
        "network_architecture": {
            "published_transport_and_resilience": [],
            "boundary": "M-501 and M-502 publish controls sequences and point matrices but do not publish a final BAS network topology, protocol transport, controller address list, I/O-card layout, terminal schedule or wiring diagram.",
        },
        "sequence_inventory": sequence_inventory,
        "control_boundaries": ["All setpoints marked adjustable remain adjustable as printed. The record does not turn schedule rows, diagrams or point-matrix templates into an installed sensor, actuator, damper, controller, terminal, wiring or address count."],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")


if __name__ == "__main__":
    main()
