"""Author source-bounded Rank 29 ground truth."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; AUDIT=ROOT/'ground_truth'; IDENT='29__vol2__030'; WORK=AUDIT/'work'/IDENT
def put(n,v):WORK.mkdir(parents=True,exist_ok=True);(WORK/(n+'.json')).write_text(json.dumps(v,indent=2)+'\n')
def a(i,p,b,t):return {'id':i,'page':p,'bbox':b,'expected':t,'mode':'contains'}
def pages():
 def f(p):
  if p==1:return 'Cover/general-notes sheet visually reviewed; Syracuse VA EHRM identity retained.'
  if p in {84,85,86}:return 'Dense mechanical schedule sheet visually reviewed; literal fan-coil rows and schedule/control context retained separately.'
  if p==87:return 'Control-symbol/diagram source sheet visually reviewed; time-clock and controls context retained separately.'
  if 20<=p<=30:return 'Mechanical/plumbing detail or plan source sheet visually reviewed as coordinated context.'
  return 'General/architectural/structural/electrical/mechanical source sheet visually reviewed as coordinated context.'
 return [{'page':p,'sheet_context':f'PDF {p:02d}','render':f'reviews/{IDENT}/p{p}-p{p}-full-poppler.png','finding':f(p)} for p in range(1,94)]
def tab():
 rows=['25,700 30,000 1,2']
 return {'id':'M601-TWO-PIPE-FCU','page':84,'sheet':'M-601','title_as_printed':'TWO-PIPE FAN COIL UNIT SCHEDULE','columns':'literal_source_row_as_printed','x_edges':[150,2900],'y_ranges':[[260,270]],'rows':rows,'row_reading_order':'left_to_right','source_row_semantics':'Literal schedule row fragment only; not plan counts, ownership, controller binding or wiring claims.'}
def audit():
 ds=[('project_identity','Cover title identifies EHRM Infrastructure Upgrades—Syracuse VA.',[['modules','metadata','project']]),('sheet_details','All 93 pages have retained visual review; M-601/M-602/M-603 schedule/control sheets are explicitly reviewed.',[['modules','metadata','visual_review_pages']]),('scale_verification','No global scale or plan-derived quantity is asserted.',[['modules','metadata','scale_semantics']]),('equipment_tags_and_classification','Three literal two-pipe fan-coil schedule rows are retained.',[['modules','equipment_reconciliation','schedule_counts']]),('schedule_rows_and_specs','The fan-coil rows are coordinate-bounded and schedule titles retain cooling/heating, damper, humidifier and fire/smoke context.',[['modules','schedules','tables']]),('point_lists_and_equipment_ownership','One literal time-clock control-symbol row is retained with source-only ownership.',[['modules','points','tables']]),('network_architecture','BACnet integration is published as an equipment requirement; final topology is not inferred.',[['modules','controls_context','network_architecture']]),('sequences_and_diagrams','Control-symbol schedule context is retained; no unstated sequence is invented.',[['modules','controls_context','sequence_inventory']]),('space_sensors_and_zones','BACnet/temperature/humidity interface requirement and controls-symbol context are retained without device counts.',[['modules','controls_context','sensors_and_control_symbol_context']]),('source_limitations_and_conflicts','Point, network, controller, wiring and physical-count limits are explicit.',[['modules','supporting_evidence','source_limitations']]),('all_page_visual_review','Every page has a Poppler full-page review render.',[['page_review']]),('independent_corroboration','All retained rows/assertions are rechecked with MuPDF and Poppler.',[['module_source_sha256']])]
 return [{'id':i,'result':'reviewed_with_source_limitations_recorded','finding':f,'evidence':e} for i,f,e in ds]
def main():
 r=pages()
 put('metadata',{'document_id':IDENT,'module_role':'Cover facts, visual ledger and scale boundary.','tables':[],'project':{'project_name_as_printed':'EHRM INFRASTRUCTURE UPGRADES - SYRACUSE VA','facility_as_printed':'VA NY SYRACUSE','location_as_printed':'800 IRVING AVE., SYRACUSE, NY 13210','issue_as_printed':'100% CONSTRUCTION DOCUMENTS 08/22/2025','assertion_ids':['cover-project','cover-location']},'scale_semantics':{'stated_scale_records':[],'graphic_scale_bar_status':'No global scale is asserted.','takeoff_scale_status':'No plan-derived quantity is asserted.'},'visual_review_pages':r,'assertions':[a('cover-project',1,[2525,1910,2760,1980],'EHRM INFRASTRUCTURE UPGRADES - SYRACUSE VA'),a('cover-location',1,[2525,1995,2760,2030],'VA NY SYRACUSE 800 IRVING AVE., SYRACUSE, NY 13210')]})
 put('schedules',{'document_id':IDENT,'module_role':'Literal two-pipe fan-coil schedule rows plus bounded schedule context.','tables':[tab()],'assertions':[a('m601-fcu-title',84,[1310,105,1790,155],'TWO-PIPE FAN COIL UNIT SCHEDULE'),a('m602-doas-hw',85,[550,400,1140,440],'DOAS HOT WATER HEATING COIL SCHEDULE'),a('m602-damper',85,[550,985,1120,1020],'PRESSURE RELIEF DAMPER SCHEDULE'),a('m603-fire-smoke-damper',86,[600,335,1100,375],'FIRE AND SMOKE DAMPER SCHEDULE')]})
 put('points',{'document_id':IDENT,'module_role':'Literal control-symbol row.','tables':[{'id':'M603-TIME-CLOCK','page':87,'sheet':'M-603','title_as_printed':'CONTROLS SYMBOLS','columns':'literal_source_row_as_printed','x_edges':[1165,1540],'y_ranges':[[1045,1080]],'rows':['TIME CLOCK CONTROLLING EQUIPMENT ON A SCHEDULE'],'row_reading_order':'left_to_right','source_row_semantics':'Literal control-symbol functionality only; no physical count or final ownership is implied.'}],'assertions':[]})
 put('point_applications',{'document_id':IDENT,'module_role':'Published control-symbol source-row scope.','tables':[],'ledger_mode':'literal_source_row_matrices_v1','applications':[{'id':'m603-time-clock','source_table':'M603-TIME-CLOCK','ownership_scope':'Control-symbol context only; final controller, device, address, wiring and ownership are not stated.'}],'expanded_template_counts':{'source_rows':1,'total':1},'expanded_count_warning':'One literal symbol row is not a count of devices, controllers, I/O or cables.'})
 cs=[a('m601-bacnet-interface',84,[150,775,1040,815],'PROVIDE WITH BACNET CONTROL INTERFACE. SEE SPECIFICATIONS AND CONTROL DIAGRAM FOR ADDITIONAL INFORMATION. PROVIDE WITH TEMPERATURE AND HUMIDITY SENSOR.'),a('m601-bacnet-campus',84,[150,790,1040,820],'FURNISH WITH AN ADAPTER FOR INTEGRATION WITH VA CAMPUS BMS VIA BACNET.'),a('m603-controls-symbols',87,[540,215,770,260],'CONTROLS SYMBOLS'),a('m603-time-clock',87,[1165,1045,1540,1080],'TIME CLOCK CONTROLLING EQUIPMENT ON A SCHEDULE')]
 put('controls_context',{'document_id':IDENT,'module_role':'M-601/M-603 BACnet and control-symbol context.','tables':[],'assertions':cs,'network_architecture':{'published_integration':['Selected equipment must provide a BACnet control interface and an adapter for integration with VA campus BMS.'],'assertion_ids':['m601-bacnet-interface','m601-bacnet-campus'],'boundary':'No final network topology, device addresses, object list, router/media quantities, controller/card/terminal schedule or wiring design is published.'},'sequence_inventory':[{'id':'m603-time-clock-control-context','sheet':'M-603','assertion_ids':['m603-time-clock'],'boundary':'This is a published time-clock symbol context, not an asserted system sequence.'}],'sensors_and_control_symbol_context':{'published_context':'Equipment note calls for BACnet interface and temperature/humidity sensor; M-603 provides controls symbols and a time-clock function.','assertion_ids':['m601-bacnet-interface','m603-controls-symbols'],'boundary':'No physical sensor, zone or control-device quantity is derived.'}})
 put('equipment_reconciliation',{'document_id':IDENT,'module_role':'Literal schedule row and schedule-title boundary.','tables':[],'ledger_mode':'literal_schedule_rows_v1','schedule_counts':{'tables':1,'rows':3,'interpretation':'Three literal two-pipe fan-coil rows, not installed totals.'},'control_valve_and_damper_schedule_status':{'control_valve_schedule':'No standalone control-valve schedule is claimed from the retained set.','damper_actuator_schedule':'M-602 publishes damper schedules but no standalone damper-actuator schedule is claimed.'},'source_boundary':'No physical BAS takeoff is inferred.'})
 put('supporting_evidence',{'document_id':IDENT,'module_role':'Explicit source limits.','tables':[],'source_limitations':['All 93 pages are visually reviewed. This record retains three literal fan-coil schedule rows, selected schedule titles, BACnet integration notes and one control-symbol row.','The source does not establish final field-device ownership, controller/card/terminal assignments, addresses, point database, wiring, installed quantities or a complete BAS network takeoff.','No global scale or plan-derived quantity is asserted.']})
 put('document_manifest',{'id':IDENT,'rank':29,'title':'Syracuse VA EHRM Infrastructure Controls','source_pdf':'pdf/29__vol2__030__Syracuse_VA_EHRM_Infrastructure_Controls.pdf','source_sha256':'c8a85e522ea577c37a658f099e5f3b2af619fb3a8c35ffc219b39a13b9c56367','page_count':93,'review_status':'complete_with_documented_source_limitations','scope':'Complete 93-page visual review with bounded fan-coil/damper/fire-smoke/humidifier schedule context, BACnet interface requirements and explicit no-inference limits.','reading_notes':['M-601/M-602 contain dense HVAC schedules including coil, chilled beam, pressure-relief/blast-suppression damper, humidifier and fire/smoke damper tables.','The record preserves literal rows and BACnet requirements without inventing final BAS topology.'],'verification_semantics':'Every retained row/assertion is rechecked against MuPDF and Poppler; no physical takeoff is inferred.','module_order':['metadata','schedules','points','controls_context','equipment_reconciliation','point_applications','supporting_evidence'],'module_sources':{k:[k] for k in ['metadata','schedules','points','controls_context','equipment_reconciliation','point_applications','supporting_evidence']},'requirement_audit':audit(),'page_review':[{'page':p['page'],'review_status':'complete','render':p['render'],'finding':p['finding']} for p in r],'declared_checks':[{'id':'pages','path':['page_review'],'operation':'length','expected':93}],'completion_checks':{'all_93_pages_visually_reviewed':True,'all_authoring_modules_dual_engine_verified_at_build':True,'source_limitations_explicit':True,'required_objectives_covered':True}})
if __name__=='__main__':main()
