"""Author the Rank 10 source-bounded bundle modules and full page ledger."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
AUDIT = ROOT / "ground_truth"; IDENT = "10__vol2__040"; WORK = AUDIT / "work" / IDENT
SHEETS = """M000 MD2PB.2 MD100.1 MD100.2 MD100.3 MD100.4 MD101.2 MD101.4 MD102.4 MD103.4 MD104.4 MD200.4 M1PB.2 M2PB.2 M100.0 M100.1 M100.2 M100.3 M100.4 M100.41 M100.42 M100.43 M100.44 M101.0 M101.2 M101.4 M102.0 M102.2 M200.0 M200.2 M200.4 M200.44 M201.0 M201.2 M300 M301 M302 M303 M304 M305 M306 M307 M400 M401 M402 M403 M600 M601""".split()

def write(name, value):
    WORK.mkdir(parents=True, exist_ok=True); (WORK / (name + ".json")).write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n")

def pages():
    return [{"page": i, "sheet": s, "render": f"reviews/{IDENT}/p{i}-p{i}-full-poppler.png", "finding": ("Control/sequence drawing visually reviewed and retained with bounded assertions." if s in {"M400", "M401", "M402", "M403"} else "Full-page mechanical source drawing visually reviewed; retained as source context.")} for i,s in enumerate(SHEETS,1)]

def requirement_audit():
    specs=[("project_identity","Project, facility, issue date and first sheet are bounded." ,[["modules","metadata","project"]]),("sheet_details","All 48 supplied pages have a sheet ledger and visual disposition.",[["modules","metadata","visual_review_pages"]]),("scale_verification","No global scale is asserted.",[["modules","metadata","scale_semantics"]]),("equipment_tags_and_classification","Literal selected schedule rows replace inferred installed totals.",[["modules","equipment_reconciliation","schedule_counts"]]),("schedule_rows_and_specs","The M601 phase-2 terminal-air-box schedule retains 11 full rows.",[["modules","schedules","tables"]]),("point_lists_and_equipment_ownership","No formal source point-list matrix is published; zero source rows is explicit.",[["modules","points","point_list_status"],["modules","point_applications","expanded_template_counts"]]),("network_architecture","Published FMCS/VFD/DDC integration is retained with topology boundaries.",[["modules","controls_context","network_architecture"]]),("sequences_and_diagrams","Terminal-air-box, VFD and steam monitoring clauses are bounded.",[["modules","controls_context","sequence_inventory"]]),("space_sensors_and_zones","The terminal schedule's printed control/sensor types are retained without physical counts.",[["modules","schedules","tables"]]),("source_limitations_and_conflicts","Schedule, point, topology and count limitations are explicit.",[["modules","supporting_evidence","source_limitations"]]),("all_page_visual_review","All source pages have full-page Poppler renders and findings.",[["page_review"]]),("independent_corroboration","Each authored module is independently rechecked against MuPDF and Poppler.",[["module_source_sha256"]])]
    return [{"id":a,"result":"reviewed_with_source_limitations_recorded","finding":b,"evidence":c} for a,b,c in specs]

def main():
    p=pages(); assert len(p)==48
    write("metadata_rank10", {"document_id":IDENT,"module_role":"Title-block facts, full supplied-sheet ledger, scale boundary and complete visual-review disposition.","tables":[],"project":{"project_name_as_printed":"EXPAND STERILE PROCESSING SERVICE (SPS)","facility_as_printed":"Captain James A. Lovell Federal Healthcare Center","issue_date_as_printed":"11/29/2022","assertion_ids":["r10-project","r10-facility","r10-issue-date","r10-sheet"]},"scale_semantics":{"takeoff_scale_status":"No global drawing scale is asserted across this mixed schedule, plan, detail and diagram set.","boundary":"No local scale is converted into a document-wide quantity."},"visual_review_pages":p,"assertions":[{"id":"r10-project","page":1,"bbox":[2535,1922,2789,1963],"expected":"EXPAND STERILE PROCESSING SERVICE (SPS)","mode":"exact"},{"id":"r10-facility","page":1,"bbox":[2537,2004,2760,2015],"expected":"Captain James A. Lovell Federal Healthcare Center","mode":"exact"},{"id":"r10-issue-date","page":1,"bbox":[2537,2052,2589,2064],"expected":"11/29/2022","mode":"exact"},{"id":"r10-sheet","page":1,"bbox":[2866,2032,2916,2056],"expected":"M000","mode":"exact"}]})
    write("points_rank10", {"document_id":IDENT,"module_role":"Explicit no-row point-list finding.","tables":[],"assertions":[],"point_list_status":{"formal_row_matrix":"not_published_in_supplied_drawings","finding":"FMCS/terminal-control diagrams and schedules publish point context but no conventional formal points-list row matrix.","boundary":"No I/O/device count is inferred from diagram symbols or schedule control/sensor types."}})
    write("equipment_reconciliation_rank10", {"document_id":IDENT,"module_role":"Literal selected schedule-row presentation only.","tables":[],"ledger_mode":"literal_schedule_rows_v1","schedule_counts":{"tables":1,"rows":11,"interpretation":"One selected M601 table and 11 literal rows."},"control_valve_and_damper_schedule_status":{"damper_actuator_schedule":"No standalone damper-actuator schedule title is asserted; TAB control/sensor type fields are captured.","control_valve_schedule":"No standalone CONTROL VALVE SCHEDULE is asserted."},"source_boundary":"Rows do not establish installed quantities, ownership, wiring or I/O."})
    write("point_applications_rank10", {"document_id":IDENT,"module_role":"No-row point-list disposition.","tables":[],"ledger_mode":"literal_source_row_matrices_v1","applications":[],"expanded_template_counts":{"source_rows":0,"total":0},"expanded_count_warning":"0 is the formal published point-list source-row count, not a physical BAS/device count."})
    write("supporting_evidence_rank10", {"document_id":IDENT,"module_role":"Explicit source limitations.","tables":[],"source_limitations":["Only the 11-row M601 Phase 2 terminal-air-box table is represented as transcribed schedule inventory; other reviewed schedules are source context.","M401-M403 supply detailed FMCS sequences and monitoring context but no conventional point-list matrix.","No final BAS topology, addresses, I/O cards, terminals, wiring or device count is published.","All 48 pages have full-page visual-review renders and every retained schedule cell/clause is dual-engine checked."],"text_absence_assertions":[{"id":"r10-no-control-valve-schedule","pages":list(range(1,49)),"covers_all_source_pages":True,"patterns":[r"CONTROL\\s+VALVE\\s+SCHEDULE"],"visual_review_qualification":"Native text and visual review support only the limited finding that no standalone title with this wording is present."}]})
    manifest={"id":IDENT,"rank":10,"title":"Lovell Federal Health Care Center Sterile Processing Expansion","source_pdf":"pdf/10__vol2__040__Lovell_Federal_Health_Care_Center_Sterile_Processing_Expansion.pdf","source_sha256":"2337ee9ae5483fd440d98967f23f63f8337d7f6dc8d3024cd494c29e129a1dc2","page_count":48,"review_status":"complete_with_documented_source_limitations","scope":"Complete source-bounded Rank 10 ground truth: all-page visual review, metadata/scale boundaries, 11 M601 Phase-2 TAB schedule rows, and 20 exact M401-M403 FMCS/VFD/steam-monitoring clauses. No physical takeoff, I/O, topology, wiring or untranscribed schedule corpus is invented.","reading_notes":["M601 provides a dense terminal-air-box schedule with airflow, reheat, control and sensor-type fields.","M401-M403 provide detailed FMCS terminal, VFD, report-generation, steam-meter and trap-monitoring sequences.","No conventional point-list matrix is supplied."],"verification_semantics":"The bundle verifier rechecks every retained source fact against independent MuPDF and Poppler captures and hashes all source/render dependencies; it does not perform takeoff inference.","module_order":["metadata","schedules","points","controls_context","equipment_reconciliation","point_applications","supporting_evidence"],"module_sources":{"metadata":["metadata_rank10"],"schedules":["schedules_m601_phase2_tabs"],"points":["points_rank10"],"controls_context":["controls_sequences"],"equipment_reconciliation":["equipment_reconciliation_rank10"],"point_applications":["point_applications_rank10"],"supporting_evidence":["supporting_evidence_rank10"]},"requirement_audit":requirement_audit(),"page_review":[{"page":x["page"],"review_status":"complete","render":x["render"],"finding":x["finding"]} for x in p],"declared_checks":[{"id":"r10-page-review","path":["page_review"],"operation":"length","expected":48},{"id":"r10-schedules","path":["modules","schedules","tables"],"operation":"length","expected":1},{"id":"r10-points","path":["modules","points","tables"],"operation":"length","expected":0}],"completion_checks":{"all_48_pages_visually_reviewed":True,"all_authoring_modules_dual_engine_verified_at_build":True,"source_limitations_explicit":True,"required_objectives_covered":True}}
    write("document_manifest",manifest)
if __name__ == "__main__": main()
