import { chmodSync, copyFileSync, mkdirSync, readdirSync, rmSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const packageDir = resolve(scriptDir, '..')
const output = resolve(packageDir, 'dist', 'server.js')

mkdirSync(dirname(output), { recursive: true })
copyFileSync(resolve(packageDir, 'bin.js'), output)

// Ship the same Python implementation in npm/MCP bundles. Never copy virtual
// environments, local inputs, test evidence, bytecode, or credentials.
const basSource = resolve(packageDir, '../bas_engine')
const basOutput = resolve(packageDir, 'dist/python/bas_engine')
mkdirSync(basOutput, { recursive: true })
for (const name of readdirSync(basSource)) {
  if (name.endsWith('.py') || name === 'pyproject.toml') copyFileSync(resolve(basSource, name), resolve(basOutput, name))
}

// Package only the existing VectorGrid RPC import closure, byte-for-byte.
// celltext imports bakeoff/boxfit for shared helpers; rastergrid reads a
// picture of a table (AS-153) and imports its OCR engine only when it runs, so
// without one installed it says so (`available()`) and the picture stays a
// raster region. No corpus keys, PDFs, models, virtual environments or OCR
// engine are copied.
const vectorGridFiles = [
  'sidecar/tables.py', 'sidecar/vectorgrid_rpc.py',
  'bakeoff/vectorgrid.py', 'bakeoff/celltext.py', 'bakeoff/bakeoff.py', 'bakeoff/boxfit.py',
  'bakeoff/rastergrid.py',
]
// This directory is generated by this build only. Rebuild it so a local smoke
// run's __pycache__ or stale runtime modules cannot leak into the next package.
const vectorGridOutput = resolve(packageDir, 'dist/python/vectorgrid')
rmSync(vectorGridOutput, { recursive: true, force: true })
for (const file of vectorGridFiles) {
  const target = resolve(vectorGridOutput, file)
  mkdirSync(dirname(target), { recursive: true })
  copyFileSync(resolve(packageDir, '..', file), target)
}

if (process.platform !== 'win32') {
  chmodSync(output, 0o755)
}
